;;; early-init.el --- My Emacs Early Init File -*- lexical-binding: t -*-

;; This file is not part of GNU Emacs

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Code:

;; Prevent Emacs from loading system window decorations.
;; (add-to-list 'default-frame-alist '(undecorated-round . t))
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
(setopt ns-use-proxy-icon nil)
(setopt frame-title-format nil)

;; Remove outer padding from Emacs frame.
(setopt frame-resize-pixelwise t)

;; Disable scroll-bar, tool-bar, start-up greeting message, and the help
;; message at the top of Scratch buffers.
(scroll-bar-mode -1)
(tool-bar-mode -1)
(setopt inhibit-startup-message t)
;; (setopt initial-scratch-message nil)

(when (featurep 'native-compile)
  (setopt native-comp-async-report-warnings-errors nil)
  (setopt native-comp-deferred-compilation t))

;; Designate a folder to collect all of the .eln files generated by
;; native compilation. (This is recommended by the configuration for the
;; no-litering package, which itself is configured in my init.el.)
(when (and (fboundp 'startup-redirect-eln-cache)
           (fboundp 'native-comp-available-p)
           (native-comp-available-p))
  (startup-redirect-eln-cache
   (convert-standard-filename
    (expand-file-name "var/eln-cache/" user-emacs-directory))))

(provide 'early-init)

;;; early-init.el ends here
